Lab4/Models/ControlModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Lab4.Models
{
    public class ControlModel
    {
        public string Result { get; set; }
        public string ControlElement { get; set; }
        public string Name { get; set; }
    }
}

Lab4/Models/ErrorViewModel.cs
using System;

namespace Lab4.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Lab4/Models/ResetModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace Lab4.Models
{
    public class ResetModel
    {
        [Required]
        [EmailAddress]
        public string Email { get; set; }

        public string Message { get; set; }

        public string Code { get; set; }
    }
}

Lab4/Models/SignUpModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace Lab4.Models
{
    public class SignUpModel
    {
        public string FirstName { get; set; }
        
        public string LastName { get; set; }

        public string Day { get; set; }

        public string Month { get; set; }

        public string Year { get; set; }

        public string Gender { get; set; }

        [Required]
        [EmailAddress]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string Confirm { get; set; }
    }
}

Lab4/Controllers/AccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Lab4.Models;

namespace Lab4.Controllers
{
    public class AccountController : Controller
    {

        [HttpGet]
        public IActionResult ResetPassword()
        {
            return View();
        }

        [HttpPost]
        public IActionResult ResetPassword(ResetModel model, string action)
        {
            if (model.Code == null)
            {
                if (!ModelState.IsValid)
                {
                    return View();
                }
                if (action == "Send")
                {
                    model.Message = "We have sent you a code";
                    return View("ResetContinue", model);
                }
                else
                {
                    model.Message = "";
                    return View("ResetContinue", model);
                }
            }
            else { return View("ResetEnd"); }
        }

        [HttpGet]
        public IActionResult SignUpFirst()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SignUpFirst(SignUpModel model)
        {
            if (model.Email == null)
            {
                return View("SignUpSecond");
            }

            else
            {
                if (!ModelState.IsValid)
                {
                    return View("SignUpSecond");
                }
                else { return View("SignUpResult", model); }
            }
        }

    }
}

Lab4/Controllers/ControlsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Lab4.Models;

namespace Lab4.Controllers
{
    public class ControlsController : Controller
    {
        [HttpGet]
        public IActionResult TextBox()
        {
            return View();
        }

        [HttpPost]
        public IActionResult TextBox(string TB)
        {
            ControlModel cm = new ControlModel
            {
                ControlElement = "Text Box",
                Result = TB,
                Name = "Text: "
            };
            return View("ResultControl", cm);
        }

        [HttpGet]
        public IActionResult TextArea()
        {
            return View();
        }

        [HttpPost]
        public IActionResult TextArea(string TA)
        {
            ControlModel cm = new ControlModel
            {
                ControlElement = "Text Area",
                Result = TA,
                Name = "Text: "
            };
            return View("ResultControl", cm);
        }

        [HttpGet]
        public IActionResult CheckBox()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CheckBox(bool isSelected)
        {
            ControlModel cm = new ControlModel
            {
                ControlElement = "Check Box",
                Name = "isSelected"
            };
            if (isSelected == false)
            {
                cm.Result = "False";
            }
            else
            {
                cm.Result = "True";
            }
            return View("ResultControl", cm);
        }


        [HttpGet]
        public IActionResult RadioButton()
        {
            return View();
        }

        [HttpPost]
        public IActionResult RadioButton(string month)
        {
            ControlModel cm = new ControlModel
            {
                ControlElement = "Radio",
                Result = month,
                Name = "Month: "
            };
            return View("ResultControl", cm);
        }

        [HttpGet]
        public IActionResult DropDownList()
        {
            return View();
        }

        [HttpPost]
        public IActionResult DropDownList(string month)
        {
            ControlModel cm = new ControlModel
            {
                ControlElement = "Drop-Down List",
                Result = month,
                Name = "Month: "
            };
            return View("ResultControl", cm);
        }

        [HttpGet]
        public IActionResult ListBox()
        {
            return View();
        }

        [HttpPost]
        public IActionResult ListBox(string month)
        {
            ControlModel cm = new ControlModel
            {
                ControlElement = "List Box",
                Result = month,
                Name = "Month: "
            };
            return View("ResultControl", cm);
        }
    }
}

Lab4/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Lab4.Models;

namespace Lab4.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Controls()
        {
            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Lab4/Views/Controls/CheckBox.cshtml
@{
    ViewData["Title"] = "CheckBox";
}

<h2>Check Box</h2>

<form method="post">
    <input type="checkbox" name="isSelected" value="true"/><label> isSelected</label><br />
    <input type="submit" value="submit" />
</form>

Lab4/Views/Controls/DropDownList.cshtml
@{
    ViewData["Title"] = "DropDownList";
}

<h2>Drop-Down List</h2>

<form method="post">
    <label><b>Month</b></label><br />
    <select name="month">
        <option value="January">January</option>
        <option value="February">February</option>
        <option value="March">March</option>
        <option value="April">April</option>
        <option value="May">May</option>
        <option value="June">June</option>
        <option value="July">July</option>
        <option value="August">August</option>
        <option value="September">September</option>
        <option value="October">October</option>
        <option value="November">November</option>
        <option value="December">December</option>
    </select><br />
    <input type="submit" value="submit" />
</form>

Lab4/Views/Controls/ListBox.cshtml
@{
    ViewData["Title"] = "ListBox";
}

<h2>List Box</h2>

<form method="post">
    <label><b>Month</b></label><br />
    <select name="month" size="12">
        <option value="January">January</option>
        <option value="February">February</option>
        <option value="March">March</option>
        <option value="April">April</option>
        <option value="May">May</option>
        <option value="June">June</option>
        <option value="July">July</option>
        <option value="August">August</option>
        <option value="September">September</option>
        <option value="October">October</option>
        <option value="November">November</option>
        <option value="December">December</option>
    </select><br />
    <input type="submit" value="submit" />
</form>

Lab4/Views/Controls/RadioButton.cshtml
@{
    ViewData["Title"] = "RadioButton";
}

<h2>Radio</h2>
<h3><b>Month</b></h3>

<form method="post">
    <input type="radio" name="month" value="January" />
    <span>January</span><br />
    <input type="radio" name="month" value="February" />
    <span>February</span><br />
    <input type="radio" name="month" value="March" />
    <span>March</span><br />
    <input type="radio" name="month" value="April" />
    <span>April</span><br />
    <input type="radio" name="month" value="May" />
    <span>May</span><br />
    <input type="radio" name="month" value="June" />
    <span>June</span><br />
    <input type="radio" name="month" value="July" />
    <span>July</span><br />
    <input type="radio" name="month" value="August" />
    <span>August</span><br />
    <input type="radio" name="month" value="September" />
    <span>September</span><br />
    <input type="radio" name="month" value="October" />
    <span>October</span><br />
    <input type="radio" name="month" value="November" />
    <span>November</span><br />
    <input type="radio" name="month" value="December" />
    <span>December</span><br />
    <input type="submit" value="submit" />
</form>

Lab4/Views/Controls/ResultControl.cshtml
@model Lab4.Models.ControlModel
@{
    ViewData["Title"] = "ResultControl";
}

<h2>@Model.ControlElement</h2>

<p>@Model.Name  @Model.Result</p>

Lab4/Views/Controls/TextArea.cshtml
@{
    ViewData["Title"] = "TextArea";
}

<h2>Text Area</h2>

<form method="post">
    <textarea name="TA" ></textarea><br/>
    <input type="submit" value="submit" />
</form>

Lab4/Views/Controls/TextBox.cshtml
@{
    ViewData["Title"] = "TextBox";
}

<h2>Text Box</h2>

<form method="post">
    <input type="text" name="TB" /><br />
    <input type="submit" value="submit" />
</form>

Lab4/Views/Home/Controls.cshtml
@{
    ViewData["Title"] = "Contact";
}

<ul>
    <li><a asp-controller="Controls" asp-action="TextBox">TextBox</a></li>
    <li><a asp-controller="Controls" asp-action="TextArea">TextArea</a></li>
    <li><a asp-controller="Controls" asp-action="CheckBox">CheckBox</a></li>
    <li><a asp-controller="Controls" asp-action="RadioButton">RadioButton</a></li>
    <li><a asp-controller="Controls" asp-action="DropDownList">DropDownList</a></li>
    <li><a asp-controller="Controls" asp-action="ListBox">ListBox</a></li>
</ul>

Lab4/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<ul>
    <li><a asp-controller="Account" asp-action="SignUpFirst">Sign Up</a></li>
    <li><a asp-controller="Account" asp-action="ResetPassword">Reset Password</a></li>
</ul>

Lab4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lab4</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Lab4</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Controls">Controls</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020 - Lab4</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>